dependencies:
  # - <organization>/repo@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.5.1

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.5.1"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}