dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.5.1 # amaç sadece bunu burda tutmak bence altta kullanmak için...
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.5.1'
networks:
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
